### PR TITLE
APPS-238 fix double checkouts

### PR DESCRIPTION
**Pull request by gereons**

### CODE REVIEW

**Review by mrgrauel — COMMENTED** [review]
@gereons what do you think of fdbf25e7b16502d46f286806206b06cc2265b81a?

I don't like the association to the polling state. Isn't it better to use the `paymentState` to define the `isEnabled` state of the `doneButton`?

**Comment by gereons** [comment]
The payment state does not fully reflect the enabled/disabled state of the checkout - fulfillments and exit codes also play a role, and that is currently all summarized in the polling state.

**Comment by mrgrauel** [comment]
That is correct but then we should add a variable or function like `isCompleted` on the `checkoutProcess`. The Polling is just a mechanism we use to determine a state and not the state we are actually looking for.

Maybe this state can also be used to determine the state of `continuePolling` in the ViewModel.

What do you think?

**Comment by gereons** [comment]
177a74fb adds `isComplete`

**Review by mrgrauel — APPROVED** [review]

**Pull request merged**
