### PR TITLE
ShoppingCartCell programmatic layout

### PR DESCRIPTION
**Pull request by mobileapps23**

### CODE REVIEW

**Review by mrgrauel — CHANGES_REQUESTED** [review]
We talked about needed changes via slack. @mobileapps23 please request review as soon as you are done. Thank you

**Comment by mobileapps23** [comment]
Can't reproduce it for testing Supermarket:
image

Simulate case when image isn't loading or isn't exist for testing Supermarket:
image

Need more info about scanned product to solve the bug (best way - printed out as `CartItem` or `Product`)

**Comment by mrgrauel** [comment]
Steps to reproduce:

1. Environment: Staging
2. Shop: Aldi "STAGING Test Schweiz"
3. Select Scanner
4. Open Search 
5. Add any item in the cart

[Screenshot](https://user-images.githubusercontent.com/148758/163399153-f5f06910-5262-4b31-971d-f6e466bf8485.PNG)

Only happens for items out of this shop.

**Comment by mobileapps23** [comment]
Layout fixed:
image

**Review by mrgrauel — APPROVED** [review]

**Pull request merged**
