### PR TITLE
shopping cart indicator icons are scaled incorrectly

### PR DESCRIPTION
**Pull request by mrgrauel**
* rewrite of the cell view to make it easier to understand
* separate views in classes
* fixes various layout issues

### CODE REVIEW

**Comment by mrgrauel** [comment]
Please don't merge yet

**Comment by mobileapps23** [comment]
should weight entry position be closer to right side?
(Snabble project - item 23232327)
image


Previous state is - 
 image

**Comment by mrgrauel** [comment]
@mobileapps23 did you finish your review? I cannot re-request the review, cause you did not finish the first. Please do the review again. I fixed the issue

**Review by mobileapps23 — CHANGES_REQUESTED** [review]
Please fix layout issue for weight entry
image

**Comment by mrgrauel** [comment]
@mobileapps23 as I said it's fixed. Did you pull the latest changes?

**Pull request merged**
