### PR TITLE
PaymentMethodAdd dynamic fonts

### PR DESCRIPTION
**Pull request by mobileapps23**
Steps to check:
1. Open Profile section
2. Tap to "Payment Methods"

### CODE REVIEW

**Review by mrgrauel — CHANGES_REQUESTED** [review]
Please use the disclosure icon instead of the custom image. It's consider font for the system, that's why it changes, but that's fine. We don't want to work against the system.

**Comment by mobileapps23** [comment]
Then if maxContentSizeCategory is  .extraExtraExtraLarge, but user will set it to something bigger (Accessability XXXL for example), UI will looks this way (chevron icon will not centered by vertical):
image
Should I leave it this way?

**Comment by mrgrauel** [comment]
No but that has nothing to do with the disclosure. There seems to be another layout issue

**Comment by mobileapps23** [comment]
you're right, this issue is about height constraint of contentView, I'll fix it without custom accessoryView

**Comment by mobileapps23** [comment]
- cell's accessoryView changed back to system disclosure indicator
- deleted restrictions for max contentSizeCategory, so tableView's content scalable without layout issues

**Review by mrgrauel — APPROVED** [review]

**Pull request merged**
