### PR TITLE
Scanner section dynamic content

### PR DESCRIPTION
**Pull request by mobileapps23**
Added dynamic fonts for Scanner section:
- BarcodeEntry view
- Checkout bar
- Confirmation view
- Shopping List
- Scanner message view 

Questions:
1. Is there needed support for dynamic fonts for UISegmentedContol (Switcher between Shopping List and Shopping Cart?) It’s not system solution, but could be added

2. Should be scaled chevron down icon?
image

### CODE REVIEW

**Comment by mrgrauel** [comment]
> Is there needed support for dynamic fonts for UISegmentedContol (Switcher between Shopping List and Shopping Cart?) It’s not system solution, but could be added

We only work with the system solutions.

**Comment by mrgrauel** [comment]
> Should be scaled chevron down icon?

Not at the moment, because we don't scale images yet.

**Review by mrgrauel — CHANGES_REQUESTED** [review]
Please add default spacing in the shopping list cell. The Label is very close to the edge on the top and bottom.

**Comment by mobileapps23** [comment]
> Please add default spacing in the shopping list cell. The Label is very close to the edge on the top and bottom.

Can you please add a screenshot?
That's how label positioned at iPhone SE simulator:

image image

**Review by mrgrauel — APPROVED** [review]

**Pull request merged**
